version: '2'

services:

  tf-serving-server:
    container_name: tfservingdocker
    image: $USER/tensorflow-serving-devel-cpu
    command: /serving/bazel-bin/tensorflow_serving/model_servers/tensorflow_model_server --port=3000 --model_name=exp_model --model_base_path=/serving/exp_model
    networks:
      - tf_serving
    ports:
      - "3000:3000"

  tf-serving-client:
    container_name: tf-serving-client
    image: $USER/tensorflow-serving-client:latest
    networks:
      - tf_serving
    ports:
      - "5000:5000"
    environment:
      - TF_SERVER_NAME=tf-serving-server
      - TF_SERVER_PORT=3000
      - FLASK_SERVER_NAME=192.168.1.5
      - FLASK_SERVER_PORT=5000
      - FLASK_DEBUG=1
    depends_on:
      - tf-serving-server

networks:
  tf_serving:
    driver: bridge
